### ISSUE TITLE
Lighthouse performance test

### ISSUE THREAD

**Issue by fellyph** [MarcinKilarski/website-audit#2]
Hi @MarcinKilarski another tool, that you can use to test performance is lighthouse.

https://developers.google.com/web/tools/lighthouse/

**Comment by MarcinKilarski** [comment]
Hi Fellyph, thanks for a wonderful suggestion. I am using it every time. I am slowly adding information about all the tools and how to use them.

Feel free to add information about this tool in the relevant sections, I will be happy to add your commit to the master branch.
